steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
     - beta
     - functions
     - deploy
     - sayHello
     - --source=.
     - --runtime=nodejs8
     - --trigger-http
