steps:
  - name: 'maven'
    entrypoint: 'bash'
    args: ['./install_npm.sh']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
     - beta
     - functions
     - deploy
     - sayHello
     - --source=./function
     - --runtime=nodejs8
     - --trigger-http
